### ISSUE TITLE
Solicitud que se pueda cortar audio

### ISSUE THREAD

**Issue by jhonyesg** [Rello/audioplayer_editor#1]
Cordial saludo.

me encantaria saber si es posible crear un modulo que me permita ejemplo tengo un audio y quiero descargar solamente una franja de tiempo, que el plugin pueda hacer la seleccion de incion y fin y me descargue ese fragmento de audio.

quedo atento a la respuesta de la comunidad.

**Comment by Rello** [comment]
hello,
thank you for your request. unfortunately this is not so easy an not in scope of audio player
