### ISSUE TITLE
I don't see any change after installting

### ISSUE THREAD

**Issue by DanielSiepmann** [Rello/audioplayer_editor#3]
I'm running Nextcloud 20.0.5, Music 0.17.3 and 0.3.0 of your plugin.

Where exactly should it be integrated? I would expect it within the music app when clicking an "i" on the right side.
Right now I don't see anything.

Do you need further info?

**Comment by Rello** [comment]
Hello,
the addon is for the Audioplayer app - not for Music.
In AP it is integrated in the sidebar...

**Comment by DanielSiepmann** [comment]
Sorry my fault, thanks for explanation, that works out of the box as expected.
